<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>data_driven_login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f53cbb11-dbb7-497f-9c1a-75eb18eefd95</testSuiteGuid>
   <testCaseLink>
      <guid>e2ffd6ea-aa54-4ba6-bbea-40ac47b2f853</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenLogin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b423671a-9e0d-41b5-b832-ee4ca9b90efb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b423671a-9e0d-41b5-b832-ee4ca9b90efb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>fefdbd6b-0a85-404b-9fc4-68375911fdea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b423671a-9e0d-41b5-b832-ee4ca9b90efb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>5ffe57fe-aaa4-420a-8813-f9e0bafa021d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b423671a-9e0d-41b5-b832-ee4ca9b90efb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>status</value>
         <variableId>0e891d0a-36ce-4cc7-83f8-d7d0b798dcb8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
