<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Kata Sandi</name>
   <tag></tag>
   <elementGuidId>77f7948a-144c-40e5-a915-603813d89d0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div/div[2]/form/div[2]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.absolute.transition-all.cursor-text.select-none.text-neutral-500.translate-x-4.translate-y-4.text-m-medium</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;inputPassword&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>837dde25-7a91-40d8-81dd-3ebb7b75f307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute transition-all cursor-text select-none text-neutral-500 translate-x-4 translate-y-4 text-m-medium</value>
      <webElementGuid>4f49a445-147b-4541-b835-85187e53cd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>inputPassword</value>
      <webElementGuid>ab8189fb-df5b-413d-8319-6fd56649639b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kata Sandi</value>
      <webElementGuid>0240aff7-4cb8-4a87-91e7-4cdde3a07455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex h-[100vh] min-h-max flex-col dweb group&quot;]/main[@class=&quot;relative&quot;]/div[@class=&quot;flex h-full min-h-max w-full justify-center bg-cover bg-center [.dweb_&amp;]:items-center [.dweb_&amp;]:bg-neutral-50 [.dweb_&amp;]:px-[176px] [.dweb_&amp;]:py-[72px] [.mweb_&amp;]:px-6&quot;]/div[@class=&quot;[.dweb_&amp;]:m-container mx-auto flex min-h-max w-full shrink-0 items-center rounded-2xl bg-white [.dweb_&amp;]:h-[660px] [.dweb_&amp;]:justify-around [.dweb_&amp;]:gap-[48px] [.dweb_&amp;]:px-[48px] [.dweb_&amp;]:pb-[100px] [.dweb_&amp;]:pt-[127px] [.mweb_&amp;]:mt-4 [.mweb_&amp;]:flex-col&quot;]/div[@class=&quot;flex w-full shrink-0 flex-col auth_authContent__cbSDK&quot;]/form[@class=&quot;mt-6  flex w-full flex-col gap-4&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;h-[56px] relative rounded-s bg-white border file:border-0 focus-visible:outline-none file:bg-transparent disabled:cursor-not-allowed disabled:opacity-50 overflow-hidden border-neutral-500 pr-10&quot;]/label[@class=&quot;absolute transition-all cursor-text select-none text-neutral-500 translate-x-4 translate-y-4 text-m-medium&quot;]</value>
      <webElementGuid>a0a22f41-7a7d-4182-a692-16d602bdf8c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div[2]/form/div[2]/div/label</value>
      <webElementGuid>e7381220-4989-4fb6-a215-72ef2514627a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::label[1]</value>
      <webElementGuid>4219764e-bd2e-450e-9aed-3990ecf0b8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='customercare@gramedia.id'])[1]/following::label[2]</value>
      <webElementGuid>0b9d4875-54d8-4393-b9e3-715f042f22bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Kata Sandi'])[1]/preceding::label[1]</value>
      <webElementGuid>fef2552b-a009-4a0d-936f-ec81f3b48feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::label[1]</value>
      <webElementGuid>86367ca4-19ca-46ab-9ea3-2e6740eed7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kata Sandi']/parent::*</value>
      <webElementGuid>8cedb42d-dbee-4fb4-884a-c38627b8b84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>5ffcb608-ff99-4693-a446-5be40b3f387e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Kata Sandi' or . = 'Kata Sandi')]</value>
      <webElementGuid>07d5ad64-ad3d-463d-8c69-92037ca73f32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
