<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Format email tidak sesuai</name>
   <tag></tag>
   <elementGuidId>02848072-d9ac-4e57-a89a-a2b5e9b79b08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/ol/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;errorRegisterSnackbar&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4f91cd62-f6fc-404e-8bea-7cd05a95ec43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>b9725067-6d5b-46a0-9632-3c6fdc34a6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f4ad1533-8a7b-4965-83a2-a6dd962f99aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>452432ff-eb55-4a5f-b597-d545dfa8a0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>29944166-4021-42b9-b481-54d03688e035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>a2890e2d-d868-47de-a78d-e519437a1823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swipe-direction</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>5eb03a4f-1804-4d18-a082-8f1fd3b3150d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>snackbar group pointer-events-auto mx-auto flex items-center justify-between space-x-2 overflow-hidden rounded-s bg-neutral-600 px-4 py-3 shadow-3 transition-all [.dweb_&amp;]:w-[480px] [.mweb_&amp;]:w-[calc(100dvw_-_32px)] [.mweb_&amp;]:max-w-[468px] data-[state=open]:animate-in data-[state=closed]:animate-out data-[swipe=end]:animate-out data-[state=closed]:fade-out-50 data-[state=closed]:slide-out-to-bottom-[300%] data-[state=open]:slide-in-from-bottom-[300%] data-[state=closed]:[animation-duration:_.3s] data-[state=open]:[animation-duration:_.3s] data-[state=closed]:[.dweb_&amp;]:slide-out-to-top-[300%] data-[state=open]:[.dweb_&amp;]:slide-in-from-top-[300%]</value>
      <webElementGuid>d8895e8e-2c48-4931-a893-fb9d4410dda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-radix-toast-duration</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>19139b78-4f45-41b0-b8c9-d7f536246cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>errorRegisterSnackbar</value>
      <webElementGuid>1e8b565c-f96b-4588-99ba-ee8c2ee7c60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Format email tidak sesuai.</value>
      <webElementGuid>ca8a6e93-8314-40ac-8f41-f032d5777ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex h-[100vh] min-h-max flex-col dweb group&quot;]/div[2]/ol[@class=&quot;snackbar-viewport fixed bottom-12 z-[60] mx-auto flex max-h-screen w-full max-w-[500px] flex-col-reverse items-center [.dweb_&amp;]:bottom-auto [.dweb_&amp;]:top-[88px] [.dweb_&amp;]:max-w-[100%] [.dweb_&amp;]:flex-col&quot;]/li[@class=&quot;snackbar group pointer-events-auto mx-auto flex items-center justify-between space-x-2 overflow-hidden rounded-s bg-neutral-600 px-4 py-3 shadow-3 transition-all [.dweb_&amp;]:w-[480px] [.mweb_&amp;]:w-[calc(100dvw_-_32px)] [.mweb_&amp;]:max-w-[468px] data-[state=open]:animate-in data-[state=closed]:animate-out data-[swipe=end]:animate-out data-[state=closed]:fade-out-50 data-[state=closed]:slide-out-to-bottom-[300%] data-[state=open]:slide-in-from-bottom-[300%] data-[state=closed]:[animation-duration:_.3s] data-[state=open]:[animation-duration:_.3s] data-[state=closed]:[.dweb_&amp;]:slide-out-to-top-[300%] data-[state=open]:[.dweb_&amp;]:slide-in-from-top-[300%]&quot;]</value>
      <webElementGuid>ad4ce08c-832b-4415-aafb-415759861809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/ol/li</value>
      <webElementGuid>725d9035-5610-4c7f-bdbe-69b6420746ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::li[1]</value>
      <webElementGuid>74ec8c38-7a51-46a4-a98e-61b1d3472f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk dengan MyValue'])[1]/following::li[1]</value>
      <webElementGuid>a0bf6929-d8f2-4541-875f-8f97fce56d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi untukmu'])[1]/preceding::li[1]</value>
      <webElementGuid>00c56fa1-02a6-47cc-a2fd-d481856e4aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>94ba380c-7d6f-4705-a7d4-67cb6e3ebef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Format email tidak sesuai.' or . = 'Format email tidak sesuai.')]</value>
      <webElementGuid>5f4cb09b-5170-4f08-8d00-289343c9e573</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
