<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_sort</name>
   <tag></tag>
   <elementGuidId>0bc7e4cc-7d9d-40a9-b89c-ad527ebaa1d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.bg-transparent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.bg-transparent</value>
      <webElementGuid>d953d471-95e4-4282-8748-40bb737610c3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
