<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>filter_terpopuler</name>
   <tag></tag>
   <elementGuidId>cce5b02f-ee08-488a-87d2-518559e92cf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[.='Terpopuler']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[.='Terpopuler']</value>
      <webElementGuid>1c72c824-863a-4666-8edd-998a81c9581e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
