<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Ilmu Komputer</name>
   <tag></tag>
   <elementGuidId>740b0012-5248-499b-b9b7-98974ddf9369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.truncate.text-4xl-extrabold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div[2]/div[2]/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;productListTitle&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>606b611b-1a8a-4615-9dc9-465adf6987cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncate text-4xl-extrabold</value>
      <webElementGuid>0c3c3fe0-2269-4fbb-8b49-9e6c18df4f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>productListTitle</value>
      <webElementGuid>cff8928a-95e0-4cbb-a0f1-4c37c033b5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ilmu Komputer</value>
      <webElementGuid>f191c61e-db0b-4f02-b9e7-0442c6ba8458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex min-h-[100dvh] flex-col dweb group&quot;]/main[@class=&quot;relative mt-[120px]&quot;]/div[@class=&quot;[.dweb_&amp;]:m-container relative mx-auto flex space-x-8 px-4&quot;]/div[@class=&quot;w-full min-w-0 flex-grow&quot;]/div[@class=&quot;hidden h-[56px] items-center gap-4 [.dweb_&amp;]:flex&quot;]/h1[@class=&quot;truncate text-4xl-extrabold&quot;]</value>
      <webElementGuid>e77ffa71-7bc6-44fe-b23b-2250784ed8e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div[2]/div/h1</value>
      <webElementGuid>9254c4bf-d1e9-49e4-b14a-9865e9358540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hanya yang tersedia'])[1]/following::h1[1]</value>
      <webElementGuid>64631b65-db9f-475d-ac77-f2a4f7716bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stok'])[1]/following::h1[1]</value>
      <webElementGuid>1b1eb9e7-7735-40be-b1eb-9ffc94f841db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urutkan'])[1]/preceding::h1[1]</value>
      <webElementGuid>81ce18af-57f5-43fa-8acd-b307cebca05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terbaru'])[1]/preceding::h1[1]</value>
      <webElementGuid>b44ea988-e51a-429e-ab61-8c5cd77c7ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>51a57b84-056a-40b8-a599-4fd84720d083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Ilmu Komputer' or . = 'Ilmu Komputer')]</value>
      <webElementGuid>7b290355-9e1f-4604-8f77-71e9c499bd50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
