<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cek Email</name>
   <tag></tag>
   <elementGuidId>5124ce7f-6839-4c00-9bbc-9179859445af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r3:']/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;checkEmail&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02bbcced-561d-4aa8-981a-38782ac5febc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative inline-flex items-center justify-center transition-colors focus-visible:outline-none disabled:pointer-events-none [&amp;:not(.button--loading)]:disabled:opacity-50 bg-brand-500 text-white [.dweb_&amp;]:hover:bg-brand-700 active:bg-brand-600 [&amp;:not(.button--loading)]:disabled:bg-neutral-200 [&amp;:not(.button--loading)]:disabled:text-white py-3 px-4 text-s-extrabold rounded-s mt-5 w-full</value>
      <webElementGuid>e7869c1d-25bd-4341-8c2a-d466257af251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>checkEmail</value>
      <webElementGuid>3e56c280-f22b-4b8c-974c-bb2941ff6fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-element</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>b07479f0-234c-4a02-b44c-bfef6e70ea32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-source-file</name>
      <type>Main</type>
      <value>ForgotPasswordSuccessContent.tsx</value>
      <webElementGuid>a462e3fe-5358-41d7-857a-5a7f7c650bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cek Email</value>
      <webElementGuid>d4c6a437-ca30-486c-b658-97ea7bb650ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r3:&quot;)/div[1]/button[@class=&quot;relative inline-flex items-center justify-center transition-colors focus-visible:outline-none disabled:pointer-events-none [&amp;:not(.button--loading)]:disabled:opacity-50 bg-brand-500 text-white [.dweb_&amp;]:hover:bg-brand-700 active:bg-brand-600 [&amp;:not(.button--loading)]:disabled:bg-neutral-200 [&amp;:not(.button--loading)]:disabled:text-white py-3 px-4 text-s-extrabold rounded-s mt-5 w-full&quot;]</value>
      <webElementGuid>a00a9b51-499e-43a7-8cc9-7137e573c21a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r3:']/div/button</value>
      <webElementGuid>b1340d9b-1f5b-445d-b36b-0978af81c517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Telah Terkirim!'])[1]/following::button[1]</value>
      <webElementGuid>365aa741-ad74-4e48-a983-a955187a9b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi untukmu'])[1]/following::button[1]</value>
      <webElementGuid>8e0bd7d5-a88a-4436-9185-2cbbb141d36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/button</value>
      <webElementGuid>213ff83d-3466-4a38-a14e-f61346bf9f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Cek Email' or . = 'Cek Email')]</value>
      <webElementGuid>adfef453-51c6-4ae1-a50b-2a210bcafd90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
