<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Terpopuler</name>
   <tag></tag>
   <elementGuidId>00579f4d-c50f-4389-892a-a89a8d17b082</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div[2]/div[2]/div[2]/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;productListFilterBubble\#1&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>980ae656-9a07-40b2-bf5a-cbbbdfc706ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncate</value>
      <webElementGuid>3bc67788-457e-4e1e-a495-8b7d2acc2ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terpopuler</value>
      <webElementGuid>b3afe44a-86b6-4350-975e-f33e479cc7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex min-h-[100dvh] flex-col dweb group&quot;]/main[@class=&quot;relative mt-[120px]&quot;]/div[@class=&quot;[.dweb_&amp;]:m-container relative mx-auto flex space-x-8 px-4&quot;]/div[@class=&quot;w-full min-w-0 flex-grow&quot;]/div[@class=&quot;hide-scrollbar mt-0 flex gap-x-2 overflow-auto [.dweb_&amp;]:mt-4 [.dweb_&amp;]:gap-x-4&quot;]/button[@class=&quot;rounded-infinity flex items-center space-x-1 border px-4 py-2 text-s-medium outline-none transition border-neutral-700 bg-neutral-150 text-neutral-700 [.dweb_&amp;]:hover:border-neutral-700 focus-visible:border-neutral-150 active:border-neutral-150 [.dweb_&amp;]:hover:bg-neutral-50 focus-visible:bg-neutral-50 active:bg-neutral-50 pl-3 whitespace-nowrap grow-0&quot;]/span[@class=&quot;truncate&quot;]</value>
      <webElementGuid>5b7edff6-1bb9-4fc7-a798-bf6557a083c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div[2]/div[2]/button[2]/span</value>
      <webElementGuid>638dda75-e3f6-41a2-9af0-aecf8dc7b379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terpopuler'])[1]/following::span[1]</value>
      <webElementGuid>1cdc7cb9-3c2f-4f92-b400-476742a5c629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urutkan'])[1]/following::span[3]</value>
      <webElementGuid>7fd73115-d46b-40d2-9ad5-cc0d6e14eb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stok Tersedia'])[1]/preceding::span[1]</value>
      <webElementGuid>4bfbb862-ad3f-44da-92d7-2f14b649b767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daniel Goleman'])[1]/preceding::span[2]</value>
      <webElementGuid>64bb2e45-c312-4381-9aa3-c3427724c5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>35e796aa-e94b-4bad-b478-2d90ac8df7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Terpopuler' or . = 'Terpopuler')]</value>
      <webElementGuid>5fdf4d38-abaa-4bf6-a5e1-d746c2e072d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
