<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Harga Terendah</name>
   <tag></tag>
   <elementGuidId>d95ea1d3-de5a-4b27-8439-27b6d506b58e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div[2]/div[2]/div[2]/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;productListFilterBubble\#1&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1a866990-2173-477d-b9a4-8319f0000abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncate</value>
      <webElementGuid>1e18dd8c-1c0f-46da-bb73-a397c9246107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Harga Terendah</value>
      <webElementGuid>4d05edac-2708-48ec-b595-2d7e189ff899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex min-h-[100dvh] flex-col dweb group&quot;]/main[@class=&quot;relative mt-[120px]&quot;]/div[@class=&quot;[.dweb_&amp;]:m-container relative mx-auto flex space-x-8 px-4&quot;]/div[@class=&quot;w-full min-w-0 flex-grow&quot;]/div[@class=&quot;hide-scrollbar mt-0 flex gap-x-2 overflow-auto [.dweb_&amp;]:mt-4 [.dweb_&amp;]:gap-x-4&quot;]/button[@class=&quot;rounded-infinity flex items-center space-x-1 border px-4 py-2 text-s-medium outline-none transition border-neutral-700 bg-neutral-150 text-neutral-700 [.dweb_&amp;]:hover:border-neutral-700 focus-visible:border-neutral-150 active:border-neutral-150 [.dweb_&amp;]:hover:bg-neutral-50 focus-visible:bg-neutral-50 active:bg-neutral-50 pl-3 whitespace-nowrap grow-0&quot;]/span[@class=&quot;truncate&quot;]</value>
      <webElementGuid>05713923-2724-4f02-97ac-d3d4230298e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div[2]/div[2]/button[2]/span</value>
      <webElementGuid>a7df2706-e617-45dc-b0be-a91e72bd3554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Terendah'])[1]/following::span[1]</value>
      <webElementGuid>c64505be-cffa-49c3-9fef-e106c5905877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urutkan'])[1]/following::span[3]</value>
      <webElementGuid>8c464dbf-fadd-45dc-8d5f-967c4cacfe64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stok Tersedia'])[1]/preceding::span[1]</value>
      <webElementGuid>e96287c8-4a8c-458b-ab91-9380a3eefac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rofi Ali Majid'])[1]/preceding::span[2]</value>
      <webElementGuid>55f8182e-fd0c-4b80-88b4-c34e3b64f0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>d80dcce9-6213-4cb6-8325-e8bb8c4f4f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Harga Terendah' or . = 'Harga Terendah')]</value>
      <webElementGuid>b0f0c979-a780-4621-92fd-d58fe866c0f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
