<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ilmu Komputer</name>
   <tag></tag>
   <elementGuidId>eec1969e-6185-480f-94b5-a61cfc437031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/header/div[2]/div/div[4]/div/div[2]/section[2]/div/div/div/div/div[26]/a[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ilmu Komputer&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07c7c863-c767-45e6-b7d0-1a311abfd537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-category-item flex items-center rounded-xs px-4 py-3 text-neutral-700 hover:bg-neutral-50 [.dweb_&amp;]:px-3 [.dweb_&amp;]:py-2 [.dweb_&amp;]:active:text-s-extrabold text-s-medium</value>
      <webElementGuid>9d2d936e-f4eb-490a-a52e-850b7e67ab36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>subcategory2#5</value>
      <webElementGuid>ed0e2e82-e20c-4e37-9e6d-7d44a82bc726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-element</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>b2fb1291-8d59-4450-9bc2-db5c5c660924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-component</name>
      <type>Main</type>
      <value>NavbarCategoryItem</value>
      <webElementGuid>f8a396fb-3db3-4a4f-8caa-24ecd4436e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-source-file</name>
      <type>Main</type>
      <value>NavbarCategoryItem.tsx</value>
      <webElementGuid>7e741ae9-9e05-477a-afaf-19e346dbb1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.gramedia.com/categories/buku/komputer-teknologi/ilmu-komputer?is_available_only=true</value>
      <webElementGuid>41fbebbe-8571-4418-920e-766be42a9495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ilmu Komputer</value>
      <webElementGuid>82ae8acc-68dc-4280-8dbb-9126772031ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex min-h-[100dvh] flex-col dweb group&quot;]/header[@class=&quot;fixed top-0 z-40 w-full bg-white&quot;]/div[@class=&quot;l-container mx-auto flex flex-col justify-center px-4&quot;]/div[@class=&quot;mb-3 mt-4 flex items-center&quot;]/div[@class=&quot;fixed left-0 top-[120px] z-10 w-full overflow-hidden rounded-b-xl bg-white&quot;]/div[@class=&quot;relative h-full&quot;]/div[@class=&quot;flex-column flex h-full px-4 pt-5&quot;]/section[@class=&quot;h-full flex-grow pb-4&quot;]/div[@class=&quot;relative overflow-hidden h-full&quot;]/div[@class=&quot;h-full w-full rounded-[inherit]&quot;]/div[1]/div[@class=&quot;columns-3&quot;]/div[@class=&quot;mb-8 overflow-hidden align-top&quot;]/a[@class=&quot;navbar-category-item flex items-center rounded-xs px-4 py-3 text-neutral-700 hover:bg-neutral-50 [.dweb_&amp;]:px-3 [.dweb_&amp;]:py-2 [.dweb_&amp;]:active:text-s-extrabold text-s-medium&quot;]</value>
      <webElementGuid>6b865a66-c7f1-4cf3-a1c6-5357acdb2003</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/header/div[2]/div/div[4]/div/div[2]/section[2]/div/div/div/div/div[26]/a[7]</value>
      <webElementGuid>0c7a59b6-624a-4e3b-988b-46ca7b55780e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hacking'])[1]/following::a[1]</value>
      <webElementGuid>2c5af706-ce04-4f7a-934f-d054fce06202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desain, Grafik &amp; Media'])[1]/following::a[2]</value>
      <webElementGuid>6346730e-2772-4fbf-a5b1-b3cbd4b3cf6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Internet'])[1]/preceding::a[1]</value>
      <webElementGuid>0b910765-656f-4a75-8b85-ab6d8b1327fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.gramedia.com/categories/buku/komputer-teknologi/ilmu-komputer?is_available_only=true')]</value>
      <webElementGuid>53454afb-3472-4663-b04e-5f88c3655eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/a[7]</value>
      <webElementGuid>9d836e84-bab0-4365-bd23-be66ca249e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.gramedia.com/categories/buku/komputer-teknologi/ilmu-komputer?is_available_only=true' and (text() = 'Ilmu Komputer' or . = 'Ilmu Komputer')]</value>
      <webElementGuid>eca7aafc-8767-41b3-9f59-fdbf92512ea7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
