<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>d2895a88-4811-4f14-afa3-c1d32e9d7f3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ins-close-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='close-button-1454703513202']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;×&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f8f693bc-b5ee-483d-b3ec-5522b706b9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ins-close-button</value>
      <webElementGuid>d950a98e-8f4c-4320-b3f9-048c3fd0e779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>11d7cf90-08db-4d98-84f3-857c85594d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-button-1454703513202&quot;)/span[@class=&quot;ins-close-button&quot;]</value>
      <webElementGuid>2d7b81b6-94be-4d18-9830-2952d4ac4226</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='close-button-1454703513202']/span</value>
      <webElementGuid>c2641f10-7d53-459f-9347-bfafa04b212f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download aplikasi Gramedia.com yang tersedia di seluruh perangkat iOS dan Android'])[1]/following::span[1]</value>
      <webElementGuid>febca2b6-c315-40d0-a05c-c8d738b19b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aplikasi Seluler Kami'])[1]/following::span[1]</value>
      <webElementGuid>2937e5f9-24e3-4541-8f76-d6542b809998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>6fc6ce18-fe2a-4246-bfa9-3cb46d43214b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>17655297-8064-4063-8e6b-d1cdbdffe045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>a2ce68ef-293c-4dc9-9b67-2071b3a328e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
