<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Produk (158)</name>
   <tag></tag>
   <elementGuidId>a8da4394-5497-40bb-a8be-4a1f51bc4ebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='radix-:r4:-trigger-product']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;productListSearchTabsProduct&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02cd32df-41c6-44e0-95ca-381a974be66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6ea04741-9047-4ca6-b543-0ab5f2bd47c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>3f75547d-8ccd-44b4-8d1a-77b2b79cdcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7bb34a08-fd4e-4b5c-8209-98d20098924c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r4:-content-product</value>
      <webElementGuid>f87532a6-9207-4dc4-9571-5525c9a6f6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>4e078288-3501-4d5f-b6a5-8719232247b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:r4:-trigger-product</value>
      <webElementGuid>ba16a01d-0b1e-479d-9d37-661fd1660df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center whitespace-nowrap py-2 px-3 h-9 rounded-infinity text-s-medium bg-neutral-50 text-neutral-700 focus-visible:outline-none focus-visible:bg-neutral-200 active:bg-neutral-200 [.dweb_&amp;]:data-[state=inactive]:hover:bg-neutral-200 [.dweb_&amp;]:data-[state=active]:hover:bg-neutral-600 data-[state=active]:text-white data-[state=active]:bg-neutral-700 grow truncate [.dweb_&amp;]:w-[188px]</value>
      <webElementGuid>c2f52ad4-846f-4f37-b20e-8e0a27e6ceda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>productListSearchTabsProduct</value>
      <webElementGuid>b040ba48-8e92-403d-87cb-fdc9a886bc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2f5dd2ff-58dd-4441-9b3b-c14917c51fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>f79f16ec-30a8-45f7-af6c-5f355d44904e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Produk (158)</value>
      <webElementGuid>b936987d-7762-4529-9e71-b891a76e69f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r4:-trigger-product&quot;)</value>
      <webElementGuid>93034d52-b004-4d66-85bc-77a75e2ccc6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='radix-:r4:-trigger-product']</value>
      <webElementGuid>a1fb005a-baff-418a-ba21-23ef88a1342c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div/div/div/button</value>
      <webElementGuid>ecd38566-1c43-49bc-84cd-5aff747c9188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hanya yang tersedia'])[1]/following::button[1]</value>
      <webElementGuid>c8de37dd-84ff-4543-8f75-ba73867defd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stok'])[1]/following::button[2]</value>
      <webElementGuid>95cf8b32-06f1-4b28-8620-9fe13dfccef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urutkan'])[1]/preceding::button[2]</value>
      <webElementGuid>f9d24641-a1ce-4d68-973f-425c148fb5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Produk']/parent::*</value>
      <webElementGuid>1695315b-46ff-4d97-95f7-431194630345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/button</value>
      <webElementGuid>80e9d40a-119d-4e95-9da3-01b7fbf545f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'radix-:r4:-trigger-product' and (text() = 'Produk (158)' or . = 'Produk (158)')]</value>
      <webElementGuid>472f41a3-2a21-4cf9-a5f0-9eaa03b952ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
