<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__ins-wrap-block-16401899775510</name>
   <tag></tag>
   <elementGuidId>a2c62ef9-8033-4120-9604-5be519ccc568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ins-wrap-block-16401899775510</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ins-wrap-block-16401899775510']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ins-wrap-block-16401899775510</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f11ecbc-6937-4a98-8b05-15dec40bea7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ins-wrap-block-16401899775510</value>
      <webElementGuid>c68c76a2-71ce-41e9-9ee7-4c04f8d25dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ins-element-wrap ins-layout ins-erase-container ins-add-element-area ins-element-select-menu ins-selectable-element ins-selected-layout ins-reset-padding</value>
      <webElementGuid>b08a594b-746f-468f-aa33-612040fdcbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product-name</name>
      <type>Main</type>
      <value>RESPONSIVE_BANNER</value>
      <webElementGuid>c02fac4e-4575-4bc8-8509-2ac3c72c8bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-default-text</name>
      <type>Main</type>
      <value>TEXT HERE</value>
      <webElementGuid>57ad304e-1847-4ad7-83d3-7a786786d1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-block-config</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>ba8ec568-4041-4d4c-a81a-f542aefb107d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min-width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>928dcb49-d8fc-4ee2-9d7d-1b3f687fb2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unique-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5298cc5e-42f5-418f-ae9a-14160119ac41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min-height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>f749dcee-24cf-40e3-832a-9333768aaac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ins-wrap-block-16401899775510&quot;)</value>
      <webElementGuid>089c2c1f-4a07-464f-8042-94ab17140dd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ins-wrap-block-16401899775510']</value>
      <webElementGuid>cbbd2330-716e-4fbf-802c-340fcc4fa66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ins-layout-block-wrapper-16401899775510']/div</value>
      <webElementGuid>4c9897b7-05d5-4bf9-9305-bbd8b5b39125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[27]</value>
      <webElementGuid>1849f9d3-8c1f-4645-86ba-05ad306b931c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::div[4]</value>
      <webElementGuid>3ebb6bb7-2f13-4d4a-9af9-67770ccbe4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>49b0fccd-2569-45ac-84fa-f8673ea6c31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ins-wrap-block-16401899775510']</value>
      <webElementGuid>ca6bc26b-7400-44b7-8323-1cbe83ed3045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
