<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kategori_SearchInput_input__hmS0W bg-_b5156f</name>
   <tag></tag>
   <elementGuidId>0e9ebd40-5b01-476c-a926-3a978ad50bec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='r']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;navbarSearchBox&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>724d3c02-2d1e-4a80-a9f2-aba87630e432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc93ef4b-3051-43a9-98ac-d56100e0ba0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchInput_input__hmS0W bg-background flex w-full rounded-infinity border py-2 text-s-medium placeholder:text-neutral-200 focus:border-neutral-700 focus-visible:outline-none disabled:cursor-not-allowed disabled:border-neutral-50 disabled:bg-neutral-50 disabled:text-neutral-200 disabled:opacity-50 [.dweb_&amp;]:hover:border-neutral-700 h-10 px-10 border-neutral-700 flex-grow</value>
      <webElementGuid>a0c659fe-ff0f-44e6-ba69-a2e054515df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>eeafe62a-6147-4724-b175-57188c44ef16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Produk, Judul Buku, atau Penulis</value>
      <webElementGuid>7cb31511-6668-4243-8fa9-1e70099ac25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>navbarSearchBox</value>
      <webElementGuid>12b95279-13ee-4bb4-95b4-ac2b901a9b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-element</name>
      <type>Main</type>
      <value>SearchInput</value>
      <webElementGuid>538e38b0-70f5-4ebb-99a0-ff41d2808e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-source-file</name>
      <type>Main</type>
      <value>NavbarSearchBox.tsx</value>
      <webElementGuid>1dc27563-a27a-44c5-b662-bee543cbf8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>r</value>
      <webElementGuid>641c7030-953b-4d68-8061-e8c211cc7358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex min-h-[100dvh] flex-col dweb group&quot;]/header[@class=&quot;fixed top-0 z-40 w-full bg-white&quot;]/div[@class=&quot;l-container mx-auto flex flex-col justify-center px-4&quot;]/div[@class=&quot;mb-3 mt-4 flex items-center&quot;]/div[@class=&quot;flex w-7/12 flex-grow items-center&quot;]/div[@class=&quot;mx-auto flex w-10/12 items-center space-x-4&quot;]/div[@class=&quot;w-full&quot;]/form[1]/div[@class=&quot;relative flex-grow&quot;]/input[@class=&quot;SearchInput_input__hmS0W bg-background flex w-full rounded-infinity border py-2 text-s-medium placeholder:text-neutral-200 focus:border-neutral-700 focus-visible:outline-none disabled:cursor-not-allowed disabled:border-neutral-50 disabled:bg-neutral-50 disabled:text-neutral-200 disabled:opacity-50 [.dweb_&amp;]:hover:border-neutral-700 h-10 px-10 border-neutral-700 flex-grow&quot;]</value>
      <webElementGuid>8231484c-647c-48f9-92ad-33daf82546b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='r']</value>
      <webElementGuid>41448f1b-f035-4e22-881d-b2e452c2435d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/header/div[3]/div/div[2]/div/div/form/div/input</value>
      <webElementGuid>5b87ca6c-efc2-4cf4-9661-0828b8a93961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>40e1e5e8-7f79-4aa3-92e1-8aff6dd2a0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Cari Produk, Judul Buku, atau Penulis']</value>
      <webElementGuid>b7ffa6d5-d84b-44bb-a027-de07c21bf38e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
