<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kategori_SearchInput_input__hmS0W bg-_b5156f_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>740897c2-c958-44dc-a224-46ea7d5c381c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='ramadhan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;navbarSearchBox&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44b3188c-2a85-4dfc-9a73-5995d024ff6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd74361a-18f2-4a56-b7f0-9e7973d31445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchInput_input__hmS0W bg-background flex w-full rounded-infinity border py-2 text-s-medium placeholder:text-neutral-200 focus:border-neutral-700 focus-visible:outline-none disabled:cursor-not-allowed disabled:border-neutral-50 disabled:bg-neutral-50 disabled:text-neutral-200 disabled:opacity-50 [.dweb_&amp;]:hover:border-neutral-700 h-10 px-10 border-neutral-700 flex-grow</value>
      <webElementGuid>9bf26e9c-fc5f-4def-aecb-1e59510aa8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c5035fd7-2770-4812-95da-e39d35420eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Produk, Judul Buku, atau Penulis</value>
      <webElementGuid>fe793fe5-3d5e-4f55-b1af-6498d7dd4ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>navbarSearchBox</value>
      <webElementGuid>425cb8eb-aeb4-4826-b6a1-cd70a4420b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-element</name>
      <type>Main</type>
      <value>SearchInput</value>
      <webElementGuid>71d26396-da89-4709-8eb4-f7cce8c2de0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-source-file</name>
      <type>Main</type>
      <value>NavbarSearchBox.tsx</value>
      <webElementGuid>d914a711-0240-4f98-b350-8040b49461cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ramadhan</value>
      <webElementGuid>26a4383a-4f36-4321-b3ee-76729582d9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex min-h-[100dvh] flex-col dweb group&quot;]/header[@class=&quot;fixed top-0 z-40 w-full bg-white&quot;]/div[@class=&quot;l-container mx-auto flex flex-col justify-center px-4&quot;]/div[@class=&quot;mb-3 mt-4 flex items-center&quot;]/div[@class=&quot;flex w-7/12 flex-grow items-center&quot;]/div[@class=&quot;mx-auto flex w-10/12 items-center space-x-4&quot;]/div[@class=&quot;w-full&quot;]/form[1]/div[@class=&quot;relative flex-grow&quot;]/input[@class=&quot;SearchInput_input__hmS0W bg-background flex w-full rounded-infinity border py-2 text-s-medium placeholder:text-neutral-200 focus:border-neutral-700 focus-visible:outline-none disabled:cursor-not-allowed disabled:border-neutral-50 disabled:bg-neutral-50 disabled:text-neutral-200 disabled:opacity-50 [.dweb_&amp;]:hover:border-neutral-700 h-10 px-10 border-neutral-700 flex-grow&quot;]</value>
      <webElementGuid>4f38c7ec-0ec4-4a14-9c90-5d42de7f0df9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='ramadhan']</value>
      <webElementGuid>32187344-420b-4bb5-a884-8b419c91b89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/header/div[3]/div/div[2]/div/div/form/div/input</value>
      <webElementGuid>4c414daf-84dd-4db5-9dee-89aad33b7e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2f1079a0-4a13-4fa3-94e2-a638e8721cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Cari Produk, Judul Buku, atau Penulis']</value>
      <webElementGuid>c740f818-6483-40c8-aec4-781a50b584f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
