<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kategori_SearchInput_input__hmS0W bg-_b5156f_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>e4a95d94-039e-4a49-8c00-0f490d91b0ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='ramadha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;navbarSearchBox&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a15f0e06-1576-450f-9ee0-a94acf88850b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd9a6bc2-3cf7-428c-94c8-fc5783584920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchInput_input__hmS0W bg-background flex w-full rounded-infinity border py-2 text-s-medium placeholder:text-neutral-200 focus:border-neutral-700 focus-visible:outline-none disabled:cursor-not-allowed disabled:border-neutral-50 disabled:bg-neutral-50 disabled:text-neutral-200 disabled:opacity-50 [.dweb_&amp;]:hover:border-neutral-700 h-10 px-10 border-neutral-700 flex-grow</value>
      <webElementGuid>c612fdea-12f2-4d0f-a59d-d64736a559c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1aedcaf2-c1d1-443c-ae8e-1575cdf775f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Produk, Judul Buku, atau Penulis</value>
      <webElementGuid>3d024be2-ba6e-411a-84a8-3bfad02e735a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>navbarSearchBox</value>
      <webElementGuid>9296d976-b134-4e82-be3a-ae42b259f88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-element</name>
      <type>Main</type>
      <value>SearchInput</value>
      <webElementGuid>cd90c3aa-a7ac-45b5-8ea5-1fd9c782d6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-source-file</name>
      <type>Main</type>
      <value>NavbarSearchBox.tsx</value>
      <webElementGuid>5743fa6d-4f1a-4e35-a8e2-0717581c82a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ramadha</value>
      <webElementGuid>215c802e-28db-4139-8a10-5ff19a5947be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex min-h-[100dvh] flex-col dweb group&quot;]/header[@class=&quot;fixed top-0 z-40 w-full bg-white&quot;]/div[@class=&quot;l-container mx-auto flex flex-col justify-center px-4&quot;]/div[@class=&quot;mb-3 mt-4 flex items-center&quot;]/div[@class=&quot;flex w-7/12 flex-grow items-center&quot;]/div[@class=&quot;mx-auto flex w-10/12 items-center space-x-4&quot;]/div[@class=&quot;w-full&quot;]/form[1]/div[@class=&quot;relative flex-grow&quot;]/input[@class=&quot;SearchInput_input__hmS0W bg-background flex w-full rounded-infinity border py-2 text-s-medium placeholder:text-neutral-200 focus:border-neutral-700 focus-visible:outline-none disabled:cursor-not-allowed disabled:border-neutral-50 disabled:bg-neutral-50 disabled:text-neutral-200 disabled:opacity-50 [.dweb_&amp;]:hover:border-neutral-700 h-10 px-10 border-neutral-700 flex-grow&quot;]</value>
      <webElementGuid>3ed83844-c371-41b7-b1a0-22e11c33cf34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='ramadha']</value>
      <webElementGuid>88a6dbba-b60b-463f-80d8-4f1221a07643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/header/div[3]/div/div[2]/div/div/form/div/input</value>
      <webElementGuid>93e13e28-e076-48ad-9370-859ea5e34199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4fa3ce7b-7275-4dab-b69e-21ba9b3724d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Cari Produk, Judul Buku, atau Penulis']</value>
      <webElementGuid>9ae8c781-ad7c-48dd-9c85-585ed2add3f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
