<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kirim</name>
   <tag></tag>
   <elementGuidId>93322493-b9b6-4c69-baf7-f9de88f74848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Kirim&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c2e1c1c-65e0-4d59-beb5-9dc80de6693c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative inline-flex items-center justify-center transition-colors focus-visible:outline-none disabled:pointer-events-none [&amp;:not(.button--loading)]:disabled:opacity-50 bg-brand-500 text-white [.dweb_&amp;]:hover:bg-brand-700 active:bg-brand-600 [&amp;:not(.button--loading)]:disabled:bg-neutral-200 [&amp;:not(.button--loading)]:disabled:text-white py-2 px-3 text-xs-extrabold rounded-xs auth_submitButton__aT8EH</value>
      <webElementGuid>31dae7b0-bd42-4f83-bded-28bfee2c27df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a7751fde-24e7-4194-9206-3bd2ffe50eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-element</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>259b3bb9-f9b4-468f-b1b1-66bc4af11b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-source-file</name>
      <type>Main</type>
      <value>forgot-password.tsx</value>
      <webElementGuid>e6bf6d6d-dd53-4265-8c45-6e680ef90d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim</value>
      <webElementGuid>20557ee5-d836-4924-ac01-edc827596964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex h-[100vh] min-h-max flex-col dweb group&quot;]/main[@class=&quot;relative&quot;]/div[@class=&quot;flex h-full min-h-max w-full justify-center bg-cover bg-center [.dweb_&amp;]:items-center [.dweb_&amp;]:bg-neutral-50 [.dweb_&amp;]:px-[176px] [.dweb_&amp;]:py-[72px] [.mweb_&amp;]:px-6&quot;]/div[@class=&quot;[.dweb_&amp;]:m-container mx-auto flex min-h-max w-full shrink-0 items-center rounded-2xl bg-white [.dweb_&amp;]:h-[660px] [.dweb_&amp;]:justify-around [.dweb_&amp;]:gap-[48px] [.dweb_&amp;]:px-[48px] [.dweb_&amp;]:pb-[100px] [.dweb_&amp;]:pt-[127px] [.mweb_&amp;]:mt-4 [.mweb_&amp;]:flex-col&quot;]/div[@class=&quot;flex w-full shrink-0 flex-col auth_authContent__cbSDK&quot;]/form[@class=&quot;mt-6  flex w-full flex-col gap-4&quot;]/button[@class=&quot;relative inline-flex items-center justify-center transition-colors focus-visible:outline-none disabled:pointer-events-none [&amp;:not(.button--loading)]:disabled:opacity-50 bg-brand-500 text-white [.dweb_&amp;]:hover:bg-brand-700 active:bg-brand-600 [&amp;:not(.button--loading)]:disabled:bg-neutral-200 [&amp;:not(.button--loading)]:disabled:text-white py-2 px-3 text-xs-extrabold rounded-xs auth_submitButton__aT8EH&quot;]</value>
      <webElementGuid>c16c935c-4ca6-4c46-a73e-403ef52ef40d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>afd0c739-4515-44ba-8893-5b065fb00974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div[2]/form/button</value>
      <webElementGuid>555e71de-ad2b-4ee2-9034-2bea3e42b5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::button[1]</value>
      <webElementGuid>0d0b5500-def4-4ed7-87a4-9bdb0d7eaca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='customercare@gramedia.id'])[1]/following::button[1]</value>
      <webElementGuid>59e29c7f-bf94-48f6-9a04-f59de7ff5ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi untukmu'])[1]/preceding::button[1]</value>
      <webElementGuid>0d20133d-816d-4db2-8d0e-eae5d21f332d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>15b179fd-32b8-4651-a768-d0145b59809c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Kirim' or . = 'Kirim')]</value>
      <webElementGuid>7f5d9bd5-498b-42c9-b8c5-5d81e1a7b368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
