<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>bbbda813-e9a6-4862-aada-d1586066cb57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;loginButton&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95785bc0-be59-4ef6-8f82-bcf43233649b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative inline-flex items-center justify-center transition-colors focus-visible:outline-none disabled:pointer-events-none [&amp;:not(.button--loading)]:disabled:opacity-50 bg-brand-500 text-white [.dweb_&amp;]:hover:bg-brand-700 active:bg-brand-600 [&amp;:not(.button--loading)]:disabled:bg-neutral-200 [&amp;:not(.button--loading)]:disabled:text-white py-3 px-4 text-s-extrabold rounded-s auth_submitButton__aT8EH</value>
      <webElementGuid>87cbe5fa-820c-49d8-a913-36711c160446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>loginButton</value>
      <webElementGuid>63353ade-afcc-409f-a214-1a25e5fe132d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e8a03adc-7d92-4202-8ff5-7fd574476dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-element</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>9e122d4e-c805-4f7e-a853-45e896f5db5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-source-file</name>
      <type>Main</type>
      <value>login.tsx</value>
      <webElementGuid>8a186971-bf2a-4afb-8982-34385f4f9d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>a79ae4c8-0ba9-4812-b52a-43b1496a4360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex h-[100vh] min-h-max flex-col dweb group&quot;]/main[@class=&quot;relative&quot;]/div[@class=&quot;flex h-full min-h-max w-full justify-center bg-cover bg-center [.dweb_&amp;]:items-center [.dweb_&amp;]:bg-neutral-50 [.dweb_&amp;]:px-[176px] [.dweb_&amp;]:py-[72px] [.mweb_&amp;]:px-6&quot;]/div[@class=&quot;[.dweb_&amp;]:m-container mx-auto flex min-h-max w-full shrink-0 items-center rounded-2xl bg-white [.dweb_&amp;]:h-[660px] [.dweb_&amp;]:justify-around [.dweb_&amp;]:gap-[48px] [.dweb_&amp;]:px-[48px] [.dweb_&amp;]:pb-[100px] [.dweb_&amp;]:pt-[127px] [.mweb_&amp;]:mt-4 [.mweb_&amp;]:flex-col&quot;]/div[@class=&quot;flex w-full shrink-0 flex-col auth_authContent__cbSDK&quot;]/form[@class=&quot;mt-6  flex w-full flex-col gap-4&quot;]/div[@class=&quot;flex flex-col justify-center gap-4&quot;]/button[@class=&quot;relative inline-flex items-center justify-center transition-colors focus-visible:outline-none disabled:pointer-events-none [&amp;:not(.button--loading)]:disabled:opacity-50 bg-brand-500 text-white [.dweb_&amp;]:hover:bg-brand-700 active:bg-brand-600 [&amp;:not(.button--loading)]:disabled:bg-neutral-200 [&amp;:not(.button--loading)]:disabled:text-white py-3 px-4 text-s-extrabold rounded-s auth_submitButton__aT8EH&quot;]</value>
      <webElementGuid>8e69a874-6d7f-491d-a237-a287c5d0fec8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>86066119-86ae-46b6-91a6-d4c5240f65f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div[2]/form/div[3]/button</value>
      <webElementGuid>144d0e3c-0e90-4a13-94da-860b7714c465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Kata Sandi'])[1]/following::button[1]</value>
      <webElementGuid>73cb2a24-483d-4102-ae75-4fdaa3ab539f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[1]/following::button[1]</value>
      <webElementGuid>8c136b85-2961-4b2b-b8bd-6401547dbd83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk dengan Google'])[1]/preceding::button[1]</value>
      <webElementGuid>604af772-dbd0-4652-8774-ea972860f81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>cff81a13-adaf-4321-a2dc-1fb01b680f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>9005b202-5db9-48d1-a498-50065c457da0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
