<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Daftar</name>
   <tag></tag>
   <elementGuidId>4a8ce9c0-0164-4ead-a568-f12f471de31c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/header/div[2]/div/div[3]/div/button[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;navbarRegister&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58f84e16-030d-4c34-ac0b-3d2e4730be5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>9a386ae8-4ebe-48ce-9129-5dc346bd2f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex min-h-[100dvh] flex-col dweb group&quot;]/header[@class=&quot;fixed top-0 z-40 w-full bg-white&quot;]/div[@class=&quot;l-container mx-auto px-4&quot;]/div[@class=&quot;my-4 flex items-center&quot;]/div[@class=&quot;flex w-2/12&quot;]/div[@class=&quot;ml-auto flex&quot;]/button[@class=&quot;relative inline-flex items-center justify-center transition-colors focus-visible:outline-none disabled:pointer-events-none [&amp;:not(.button--loading)]:disabled:opacity-50 bg-brand-500 text-white [.dweb_&amp;]:hover:bg-brand-700 active:bg-brand-600 [&amp;:not(.button--loading)]:disabled:bg-neutral-200 [&amp;:not(.button--loading)]:disabled:text-white py-3 px-4 text-s-extrabold rounded-s&quot;]/div[1]</value>
      <webElementGuid>9c2ffb24-1f20-4dc7-967b-914529439540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/header/div[2]/div/div[3]/div/button[2]/div</value>
      <webElementGuid>43bb2e4a-41b2-48ab-b5c5-a1b9e8330dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/following::div[1]</value>
      <webElementGuid>0d33a888-5678-4fe9-97f5-c4be61a39fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::div[8]</value>
      <webElementGuid>ee16ddfc-8a38-48d7-8c1c-7b78a442b26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Promo'])[1]/preceding::div[20]</value>
      <webElementGuid>78cebaac-6f45-4049-ae47-651fef601726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Official Store'])[1]/preceding::div[67]</value>
      <webElementGuid>6b1c5fa0-f2bb-4bc5-b6cd-514421f0ec06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>8d39b8cb-2644-4821-94e2-f8895fd7767d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/div</value>
      <webElementGuid>59c40eb5-3381-432f-8b0c-9146f27b3357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>628f75a8-3bcb-4e06-92a0-f9ef3eb6bab9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
