<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lengkap_fullname</name>
   <tag></tag>
   <elementGuidId>23aa7119-dc5f-4abd-aaa1-10befd5abe2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='fullname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fullname&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;fullname&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a4682e8-23fa-45c5-b332-68e9fc478df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-input flex-grow px-4 pb-2 pt-6 text-m-medium outline-none disabled:bg-white overflow-hidden placeholder:text-transparent</value>
      <webElementGuid>fcec19ed-45b9-471d-8b86-f5aeb2cf5f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fullname</value>
      <webElementGuid>544f4b4c-edb1-4d05-bd30-7ff1fc393a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>e35a6e2c-382f-4405-9ed9-67f51d77124e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-element</name>
      <type>Main</type>
      <value>TextInput</value>
      <webElementGuid>61452b29-34cd-4fda-a77e-52884c5c5816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sentry-source-file</name>
      <type>Main</type>
      <value>register.tsx</value>
      <webElementGuid>03d2d35f-6981-41f4-a3c4-f343ddd7ad19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex h-[100vh] min-h-max flex-col dweb group&quot;]/main[@class=&quot;relative&quot;]/div[@class=&quot;flex h-full min-h-max w-full justify-center bg-cover bg-center [.dweb_&amp;]:items-center [.dweb_&amp;]:bg-neutral-50 [.dweb_&amp;]:px-[176px] [.dweb_&amp;]:py-[72px] [.mweb_&amp;]:px-6&quot;]/div[@class=&quot;[.dweb_&amp;]:m-container mx-auto flex min-h-max w-full shrink-0 items-center rounded-2xl bg-white [.dweb_&amp;]:h-[660px] [.dweb_&amp;]:justify-around [.dweb_&amp;]:gap-[48px] [.dweb_&amp;]:px-[48px] [.dweb_&amp;]:pb-[100px] [.dweb_&amp;]:pt-[127px] [.mweb_&amp;]:mt-4 [.mweb_&amp;]:flex-col&quot;]/div[@class=&quot;flex shrink-0 flex-col pb-5 auth_authContent__cbSDK&quot;]/form[@class=&quot;mt-6  flex flex-col gap-4&quot;]/div[@class=&quot;h-[56px] relative rounded-s bg-white border file:border-0 focus-visible:outline-none file:bg-transparent disabled:cursor-not-allowed disabled:opacity-50 overflow-hidden border-neutral-500&quot;]/div[@class=&quot;flex&quot;]/input[@class=&quot;text-input flex-grow px-4 pb-2 pt-6 text-m-medium outline-none disabled:bg-white overflow-hidden placeholder:text-transparent&quot;]</value>
      <webElementGuid>236e6ece-4c7f-4775-b84a-d940a1db5e95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fullname']</value>
      <webElementGuid>695847f5-566a-49df-a6f3-0c12903f25db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div[2]/form/div[2]/div/input</value>
      <webElementGuid>2b39dbc0-0296-4fd9-af88-5fce4e06c6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>f58970cc-fcec-4671-9c0b-2ca2a12bf92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'fullname']</value>
      <webElementGuid>353db02e-34da-420c-b320-d0901a88fc7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
